# Group Reasoning

We often find ourselves, whether we like it or not,  having to work in groups, whether it is a school group project, committee work, a social club, or a community service organization. It's important, therefore, to understand the situations in which groups tend to reason badly, so that we can guard against them.

## Supposed Advantages

Since groups are made up by individuals, all of the cognitive biases that we discussed in chapter 16 affect group reasoning. There are particular biases, though, that apply only in the contexts of reasoning in groups or about groups. So, if groups are susceptible to special group biases, and tend to reason badly in certain situations, why are we so often asked to use them?

We tend to think that groups are more likely to come to more reasonable and unbiased decisions than people working alone, because groups _seem_ to have the following advantages:

1. Groups should have access to more information than single individuals do, because everyone brings something to the table, so to speak.
2. Since every individual has their own point of view, group decisions will represent more perspectives than decisions made by single individuals.
3. We have all had times when we have overlooked something important, or just not noticed a flaw in one of our plans. The more people that are considering a proposed solution, the more likely it should be that some notices a problem.
4. We are all either risk-averse or risk-seekers to various degrees. Do we really want the people on the extremes making the decisions? If those decisions are made by a group, the risk-seekers and the risk-averse members should balance each other out to form a more reasonable decision-making body.
5. There are times when we want our decisions to reflect the will of the majority of the members of the organization. Given what we know about sampling, it seems right that a group decision would more accurately reflect the general will than the decision of a single individual.


These five points should be true of groups, but they are not true of _all_ groups. We will examine particular weaknesses that groups can have, and think about ways to structure groups so that we can avoid the weaknesses while maintaining the advantages. 

## Social Loafing

There are people who are driven to succeed, and then, there are the rest of us. If you are one of those people who are driven to succeed, my guess is that you're also a person who doesn't like group work. You're probably afraid that you'll end up doing all of the work, and pulling the weight of those who fail to do their fair share.

Social loafing is the tendency for members of a group to do less work, and to do it less well, than they would if they were working alone. One reason for this is the diffusion of responsibility that we discussed in the last chapter. If all members of the group are equally responsible for the work, then the feeling of responsibility is diffused throughout the group, so that the individuals in the group each feel less responsible than they would have had they been working alone.

There are ways to reduce social loafing in group projects. They include:

1. Grading each person on how much they contributed to the project.
2. Assigning each member a particular task, so that 100% of the responsibility for completing that task falls on some particular person.
3. Including peer reviews as part of the evaluation process.

## Group Polarization

Group polarization, also called choice shift, is the tendency for people to make decisions about risks differently when in a group than when alone. When they become more risk-seeking, this is called the risky shift. When they become more risk averse, it is called the conservative, or cautious, shift.

That this occurs should surprise no one. We have all heard stories about people who have done things in mobs that they never would have considered if acting alone. For both types of shifts, being in a group magnifies the qualities of the individuals. 

There have been a number of proposed explanations for the risky shift:

1. Diffusion of responsibility might again be the cause. Feeling completely responsible for the decision should prompt one to take few chances, that is, to become more risk averse. As perceived responsibility is shared with others, the risk is also perceived as shared. [@wallach64:_diffus_respon_level_risk_takin_group]
2. Risk-seekers naturally are perceived as being more confident, and thus may persuade others to also accept the greater risk. [@collins64:_social_psych_group_proces_decis_makin]
3. It may be that risk-seekers tend to have greater status within the group, leading people to follow their lead and supporting riskier choices. [@brown03:_social_psych]
4. As groups discuss a proposed action, group members become more comfortable with the proposal, making it seem less risky. [@bateson66:_famil_group_discus_risk_takin]

Group polarization has also been shown to affect our attitudes. Students that had low levels of racial prejudice became even less prejudiced after discussing issues of race with each other. The reverse happened with more highly prejudiced students. The became even more prejudiced after discussing the same issues with each other. [@myers70:_discus_effec_racial_attit]

## Group Accuracy

The accuracy of a group depends, of course, on the type of problem and the characteristics of the particular members of the group. It's not surprising that on problems with clear right answers, a math problem, for example, groups tend to do better than the average member of the group, but worse than the best member.

## Groupthink

Groupthink is the tendency for groups to make poor decisions and judgments. This is common in groups that are highly cohesive, have dynamic leaders, and are isolated from any external input or information. Several of the studies discussed in the last chapter are relevant here, such as the Asch conformity study, the Milgram experiment, and the Stanford prison experiment. (Remember that the Stanford study was only stopped after it was viewed by an external evaluator.) Members of such groups have a strong tendency to want to please the group leader, to agree on any decision that is made, and to feel both a strong sense of invulnerability and a strong sense of being right.

In many cases, though, groups are tasked to work on problems for which there are no clear right answers. For example, a university committee might be tasked with develop a strategy for increasing enrollment, or revise the core curriculum. Groups working on problems like these can work well, but often do not. The reason is that the group decision process naturally tends to go like this:

1. Once the problem or task has been identified, a group member proposes a solution.
2. Objections are then raised to the proposed solution.
3. Another solution is proposed, and new objections are raised. This may be repeated several times.
4. Finally, a solution is proposed against which no strong objections are raised.
5. Since no one can think of a serious objection, the proposal is accepted.

There are two problems with this process. The first is that the process is biased in favor of ideas that are discussed early. The second problem is that the solution that is accepted is the first minimally acceptable solution. There may very well be better solutions that never had a chance of being considered.

## Successful Groups

Since there seem to be so many problems with groups, it's natural to wonder if there is any reason to use them, especially in education. One reason is, since graduates, once they join the work force, will have to sometimes participate in groups, students should learn the skills of successful group interaction. Another reason is that, although group work does not seem to enhance abilities to learn material in a basic sense, discussing and explaining the material does enhance the understanding of the material.

By understanding when groups reason badly, we can now identify some characteristics of successful groups. Successful groups

1. Protect the brain-storm process. That is, they do not evaluate the ideas until _all_ of the ideas have been proposed. If this isn't feasible, then another option is to initially split into sub-groups for the initial group reasoning process.
2. Set specific goals. A group cannot identify the best solution if the problem has not been made clear.
3. Get feedback, especially from outside the group.
4. Encourage dissent. If no one disagrees, then appoint someone to raise objections to the group's decision (known as the devil's advocate).
4. Reward success, to motivate finding the best solution.

## Voting

The final step in any group decision-making process is to determine the will of the group, usually done by voting. If there are only two options, then voting presents no problems — if there is a winner, then it will be absolutely clear which option it is. If there are more than two options, however, things get complicated. 

Sometimes the group's preferences are simply inconsistent. Let's imagine a small group with three people, who are considering three different options, A, B, and C. The three people rank their preferences like this:

1. A>B>C
2. B>C>A
3. C>A>B

Both persons 1 and 3 prefer A to B, so A should win over B. Persons 1 and 2 both prefer B to C, so B should win over C. A consistent preference structure should be transitive, so if A beats B, and B beats C, then A should also beat C. In this case, however, persons 2 and 3 both prefer C to A, so the ranked order looks like this: A>B>C>A, which means that A should be preferred over A!

Let's look at a fairly simple group of nine people considering three options. Imagine that the people order their preferences like this:

| 2    | 3    | 4    |
| :--- | :--- | :--- |
| A    | B    | C    |
| B    | A    | A    |
| C    | C    | B    |

That is, two people prefer A to B to C, and 3 people, B to A to C, and 4 people, C to A to B. Now, let's look at a few reasonable voting methods and see which option wins on each.

### Plurality Wins

This is the method that we use for large-scale elections in the United States. There is a single round of voting and the option with the most first place vote wins. In this case, C wins with four votes, compared to three votes vor B and 2 votes for A. The problem here is that the majority of the people place C last. C is the winner, but the majority want anything else.

### Weighted Voting

One way to avoid this problem is by using weighted voting. Here, voters, list all of their preferences. First-place vote gets the most points, second-place votes get a little less, and so on. The most common weighted voting scheme is called _Borda's scheme_, where for _n_ options, first-place votes get $n-1$ points, second-pace votes get $n-2$ points, and so on, all the way to 0 points for last-place.

In this case, A wins with 11 points, B and C are tied for second place with 8 points each.

### Preferential Voting

Here, again, voters rank all of the options. If there is an option that receives a majority of first place votes, then that option wins. If not, then the option with the fewest first-place votes is eliminated. We then look at the rankings that have the eliminated option first, and give those votes to whatever option those people ranked second. That sounds complicated but it should be easy to understand with the example. Look at the scenario again:

| 2    | 3    | 4    |
| :--- | :--- | :--- |
| A    | B    | C    |
| B    | A    | A    |
| C    | C    | B    |

A is eliminated, having only 2 first-place votes. Those two votes to to B, so B then wins 5 to 4 over C. The intuition here is that, had A not been an option, those two people would have voted for B instead.

### Approval and Negative Voting

We already have three apparently reasonable voting methods that each produces a different winner from the same set of social preferences. There are many more methods, however. For example, approval voting, where you get to give one vote to as many options as you like, like voting for all the candidates that you wouldn't mind winning.

There is also negative voting. In this case, you can give a +1 to the option you prefer, or you can give a -1 to the option that you absolutely wouldn't want to win. That provides a way for people to express their preferences who really don't care which options wins, but really care that one of them not win.

### Runoff Voting

This is common in some smaller scale elections, and avoids the problem of possibly electing the candidate that the majority would place last. It still can be problematic in certain situations. 

Imagine three candidates for office, with 17 voters having these preferences:

| 6    | 5    | 4    | 2    |
| :--: | :--: | :--: | :--: |
| A    | C    | B    | B    |
| B    | A    | C    | A    |
| C    | B    | A    | C    |

A and B each have 6 of the 17 votes, but a majority requires 9. So, there's a runoff between those two candidates, and, if nothing were to happen, then C's voters would switch to A and A would win.

Now, imagine instead that there is a debate just before the election, and A has a particularly impressive performance. The two voters in the rightmost column decide to switch their votes from B to A.

| 6    | 5    | 4    | 2    |
| :--: | :--: | :--: | :--: |
| A    | C    | B    | A    |
| B    | A    | C    | B    |
| C    | B    | A    | C    |


Now, A has 8 votes, B only 4, and C has 5. So, the runoff now is between A and C. The four voters in the third column that supported B give their votes to C, and C wins with 9 votes compared to the 8 votes for A. Curiously, A would have won had A not gained the extra support before the election!

### Best Method?

All of the methods we've discussed have their particular strengths and weaknesses. Economist Kenneth Arrow proved in 1950 that there is no method that meets certain plausible minimal conditions. These conditions are:

1. The method will produce an ordering of options for any logically possible ordering of individual preferences.
2. If voters initially prefer A to B,  changing their mind about the ranking of anything else shouldn't affect A and B.
3. If every individual prefers A to B, then the method should rank A over B.
4. The method should not be sensitive only to one person's rankings.

Arrow proved that no method meets all of these conditions. So, since there is no perfect method, which method should be used? It really depends on the circumstances. Some things that will need to be considered include the cost and complexity of the voting system and the type and extent of information that needs to be gathered. The more complex the system, the less likely voters will feel they can trust the system. A system that is too expensive is useless no matter how accurate it is.

