# Intellectual Virtues

Over the past twenty chapters, you have learned some basic tools that can make you a good critical thinker. At  this point, you should know how to:

1. Distinguish good arguments from bad arguments.
2. Use the technical  tools of logic to assess the relationships between premises and conclusions.
3. Evaluate different sources of information.
4. Identify fallacious reasoning.
5. Use the tools of basic probability theory.
6. Reason well about causation.
7. Identify the ways human psychology and situations keep us from reasoning well.
8. Make rational choices in groups and other social contexts.

The tools themselves, though, don't make a person into a good critical thinker. I'm reminded of a person I knew who blamed his poor golf game on his old, cheap set of clubs. He finally bought a very expensive set of professional clubs, and his average score got _worse_, not better. The problem was not in the tools that he had — the problem was he didn't know how to use them. Even knowing how to use the tools of critical is not enough, though. No amount of knowledge of logic, probability, or psychology will help if a person simply does not care. A good critical thinker is one who has the tools available, knows how to use them, and cares enough to use them well.

A good critical thinker is a certain kind of person, a person marked by the intellectual virtues. Being intellectually virtuous is not the same thing as being intelligent or being knowledgeable. A person may well be very intelligent and knowledgeable, but also be careless, arrogant, and closed-minded. So, what is a virtue, and more specifically, what are the intellectual virtues?

## Virtue

A virtue is a state of character that makes one better in virtue of having it. Most of the time, when people discuss virtue, they are referring to moral virtue. Think of moral virtues as the qualities that morally good people have, like honesty, charity, courage, etc. There are also character states that make a person morally worse, like dishonesty, miserliness, and son. These are called vices. 

Virtues have several aspects. First, they aim at something. In the case of the moral virtues, the aim is moral goodness. The person having the virtue is motivated to bring about that goal. Finally, the person who has the virtue can reliably succeeded at achieving the goal. For example, the courageous person is motivated to, or wants to, act courageously. Their actually succeeding in doing what courage requires can't be merely accidental, however. That's why the reliability requirement is necessary. The virtuous person can recognize situations where charity or courage is appropriate, requiring the ability to make true moral judgments about the situations in which they find themselves.

Aristotle pointed out centuries ago that one can think of virtues being on a mean. That is, courage is kind of like a midpoint between cowardice and rashness. The courageous person is not so overwhelmed with fear that he cannot act when he should, but also does not act rashly in circumstances where it would be foolish to do so.

## Intellectual Virtue

Intellectual virtues are traits that aim at things like truth, knowledge, understanding, and wisdom. The intellectually virtuous person desires these things, is motivated to achieve them, and has the qualities that enable her to do so reliably. Exercising each virtue will require certain skills, and the good judgment to know when exercising those skills is appropriate.

In _Cultivating Good Minds_ Jason Baehr  identified nine key intellectual virtues. He divides them into three useful categories:

1. Virtues required to initially motivate learning.
2. Virtues required to guide the learning.
3. Virtues required to overcome obstacles to learning.

## Motivating Learning

The first virtue is curiosity. People who are curious naturally want to gain knowledge, to learn new things, and to seek truth. The truly curious person wants more than simply to know that something is true, she wants to understand _why_ it is true. People with the virtue of curiosity seeks more than just knowledge of trivia, they seek knowledge of issues and matters that are worthy of our attention. 

The second virtue is intellectual autonomy. To be autonomous is to be independent, or self-governing. To be intellectually autonomous is to think for oneself. Intellectually autonomous people do not succumb to the bandwagon fallacy, that is, believing something merely because others believe it, nor do they change their minds simply because someone disagrees with them. The examine evidence for themselves, and decides whether the beliefs offered by others are well-supported or not.

The third virtue that motivates learning is intellectual humility. The humble person recognizes his own intellectual weaknesses and mistakes. Intellectually humble people are aware of what they don't know, and the ways that their thinking needs improvement or is prone to error. 

## Guiding Learning

The first virtue that guides learning is attentiveness. The attentive person is present in the situation. This presence is not merely physical. We all have had times when we were physically present, but distracted or "checked out." The attentive person actively and carefully listens — listens to understand, not just thinking about how to respond. Finally, the attentive person recognize the important details, and can differentiate those details from the trivial.

The next virtue is carefulness. The careful person avoids reasoning errors, and takes care to avoid falling prone to cognitive biases. In order to do this, of course, one must know that counts as a fallacy or cognitive bias.

The last virtue that guides learning is thoroughness. The thorough person is not satisfied with what is superficial; the thorough person wants to truly understand. Thoroughness demands something more than just a recounting of the facts. The thorough person desires an explanation of those facts, and an understanding of how the facts or connected.

## Overcoming Obstacles

The first virtue that is needed to overcome obstacles to learning is open-mindedness. The closed-minded person is not willing to consider alternative viewpoints or beliefs. The open-minded person is willing to consider alternatives to his own beliefs, and is not afraid to have his own beliefs criticized. It's important to recognize that one can be open-minded but still firm in his beliefs. If a belief is true, it should stand up the evidence.

Next is intellectual courage. The intellectually courageous person is willing to suffer a potential loss or harm in the pursuit of the truth. The intellectually courageous student is willing to answer questions in class, when others are too afraid of having the wrong answer. The intellectually courageous person is willing to stand up for her beliefs, even when they are unpopular.

Finally, there is intellectual tenacity. Unfortunately, learning is just hard. There are no magic formulas or secret tools that can make something like learning a second language easy. The intellectually tenacious person is wiling to stick to it. Intellectually tenacious people don't just give up when they don't understand something, or when a text is difficult to read. Intellectually tenacious people don't give up with they fail, they rethink their approaches and try again.


    
